Document: kartesio
Title: Debian kartesio Manual
Author: <insert document author here>
Abstract: This manual describes what kartesio is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kartesio/kartesio.sgml.gz

Format: postscript
Files: /usr/share/doc/kartesio/kartesio.ps.gz

Format: text
Files: /usr/share/doc/kartesio/kartesio.text.gz

Format: HTML
Index: /usr/share/doc/kartesio/html/index.html
Files: /usr/share/doc/kartesio/html/*.html
